name:  Check Pull Request to dev branch

on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  check_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: {java-version: 1.17}
      - name: Run check out script
        run: ./gradlew :app:build

      - name: Check status
        run: echo "Check build status"
      - name: Set failed if build failed
        if: failure()
        run: echo "::error::Build failed"
