name: Build and send to QA stageQa

on:
  pull_request:
    types:
      - closed
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  send_to_qa_stage:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: { java-version: 1.17 }
      - name: Build and send application stageQa to App Distribution
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        run: |
          echo "$CREDENTIAL_FILE_CONTENT" > ./app/serviceCredentialsFile.json
          echo "App type: stageQa" >> ./app/src/stage/qa/releaseNotes.txt
          echo "buildNumber=${GITHUB_RUN_NUMBER}" >> ./app/src/stage/qa/releaseNotes.txt
          ./gradlew appDistributionToQaStageQa

      - name: Check status
        run: echo "Check build status and send status"
      - name: Set failed if build failed
        if: failure()
        run: |
          echo "::error::Build or send build stageQa to App Distribution failed"
